[package]
name = "custom-selection"
version.workspace = true
edition.workspace = true

[dependencies]
leptos = { workspace = true, features = ["csr"] }
leptos-cesium = { path = "../../leptos-cesium" }
console_error_panic_hook = { workspace = true }
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }
geo-types = "0.7"
