[package]
name = "czml-streaming"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
console_error_panic_hook.workspace = true
leptos = { workspace = true, default-features = false, features = ["csr"] }
leptos-cesium = { path = "../../leptos-cesium", default-features = false, features = ["csr"] }
serde_json.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen.workspace = true
web-sys = { workspace = true, features = ["Window"] }

[features]
csr = []
